name: superheroes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^5.0.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  network_image_mock: ^2.1.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - .env

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

